env:
  global:
    - secure: QZ8/C+EwiCb2EcZkPJcWf1v2tvQHZMuJC+tlaNYYeVEbUO8SjqL/qaluB0l+x+d0sgaMZ1C0tP45+i4Pfn9SahoYZOkQvdLqKgEQ4gxY0s8ZSEOULRV3mbDqowmr3OLGXjYVzLqETdeyQn+1yJdtS1PQwajiTBfBQ9aXnMMUKRvtQDfHB/1QN9Vk9XYhAmeB/jWJwd3/t7o6oKJZVgG1B2PjYFobuQDxImyr5L7oLTGUS+77FFyyxU9qDq7megVbE1EsCC8/6rOO2lZ6I1P12sQL2psOfcBx2pNRJ5BWaMjSJxExFJ5JvWt6SQkm9poUI84i2SUeS+5p/1itVrWxPdLNSqH1otj7p+1WIFJPbybcZdZaIftajnYKA1aNSx59qP6bLHPzgdMP19u0eFmFfKp8JqeqoasfCK/BBUr3Op7LInjw/duAyW4rtfk/NthBfT7Wcv6VVy87Zp5hl/bheMVX3WkWWVWEe9gOhdkjUH4FF98vf2nLRmcWceg63FGiJQWKOhkG4Fpl8oVSMubAQh8kzvkOajtktDis6IlMBeROI85+zvKtUm342QFpdb8TVLgPFsJBn90GHXlMmdPI16s4MauRVTE/TG9LpAWFcaR9Vrnc57p4t9rJYe166ZesMQvLXVRZiV4hEer9yBeYtM5Hx/ZnB+7nF3Beq5sgJ2s=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/www.shallalist.de
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
