env:
  global:
    - secure: iSkI2X8KzSVlWlgTL4SBFwmdVu1z/rOQ0eDXq9eh1lk+I3hb7qoMle6dIWwupHoSEnsUP67ICi8pmb5cxSl5487mnsHbXRr2KMy46mdWtrBkeBFktPH7UuFy374tIGwixHYoKQgDeItk5d+5NBRYsHpasODwLCjLGSxEpUuJRikaOAJQqMEZ3fm2o+OPx7s+h8uztE/ytxNPttIPp0h+2TQ4KCLSoTbbRAvdQM9vCzfgaY259ttbYmT0KVZGxLmhr34wc60iWEfeJG9MPo2PkoYMstiCvukfMduCauxPwpjdxxJ40vhKVb9ZxKBtjKPlfrspEKX4TdLCSLTY7jBuxacCZCARPA2mMoCBT9ts80JLuzYS0przWZtjrHJAvTjAZyxOCd/Wniq3eeuhUpu+mPIhUKGT56pAqk5QutfOKcDFh8CyK2hQrjGUnCRxuKNmDHTI3uygrU4K6zxDcpbCawKRr37Vy7Q0x7K+J37P6298MPR5BLtMDgl0yLyo4YjL7tN3oIiCTLHmEFSkiuIiBTaDhnejR2S/mJxeAFmUZwOZ5TRBpHd2cHzV3ukl7yJLQUbnxoHJ3y0h8renrpj2YA3Ep/Mc+pxvgx8nNYrx1S/WBW/f0DonUftnrfknRPfsCrOiNE2T4fKtewUF5F0yYYg1KaNSVRDR3Q1I36svmPc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/www.shallalist.de
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
