env:
  global:
    - secure: o5HFe6jXh4Q+zFOt2diexLc0wS/EKuuyWTwIln1szscIe0qVq/WBvZniT0WFDyjyhGbNwZzjmPL0APXpvE0JlVGNYQitmCvgz8g8CvDwcz6tkm9sQB+RJeHhIj25ErP+bwrU+qI8qppWvCVzFlgDiMy9WskZ5ox5fraX/iLtW8okBlyMDrtrGNRdpkUG+O0wSILHXMVRxMqz2/+B+Hf4uTsdAwqpuTZfd52EbmNgfhd/2BKNYgQY6AfpHch1+8CvRuNjJYOipzjAI4aiq1N88y9YY2iCQUtanwsMZy5F1DWBpB8fn3FMapznXAXkMpGvRzj3JUTV/yEATzXP7gDiQthBrjUEOM2cB1JJN9qUt0r5GLA57IOoRFxnFi5UmcRrrmLkuFftAzn7gI6NW91nQ2YlxOJrGLLdqfplGGgAG/GaQ6THLzu/hqxj61fyx/trCcjK4lVQJ9TWOp/5HWYC+eEwfgc8K3IzB11/5TLfI6mvgEYIyzQn456ikpzNf6Z8L6tNxZocI59JbW2ZrXiLBxc3iygUWYXZXMdzWX2UwGl/rbK7tQGZmntzJkj+TefB4eYSIOBdvC/V1J8Y8y+FFoOyLmSk9QeXzSwnaRjTEpTyfR/8MXgBAdXJpfLGSDSDr7nIQ1dPPUU2fB6W2M4Bjzv7qjrbU89/y55hW7uFePs=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/www.shallalist.de
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
