env:
  global:
    - secure: jZ3de3oYlBUSrWZiOsnoEdVwUChA9SEQF4iwf3hlezmaNWe7hj0Y92Z1MjkRONuW3velQbigyiIm4Z0a/vwJvPX2HV7TuWzMuHskENTwgGzHex2HVC6AeUbFlVf0s/Dfcnw+z5ltDlT5L4huGfXKVW8eVy937ZPPUG5R+MEdJXq8OlUSIfcRcOn9r90G9at2jhBacJKjqfedwSo88FcPF0OqMaF7It9u4LDWdFApzwr9pbnYjviOSHC6PlBAR/XtWt1QyY3akGFsk5akIRA7X5AzF9AtyyTbRq655KO4IVqmqCxCXCgOR71HMk+S7/UvhTlPmhzuL8CJAFV6VDuF3Nn3VwY9IVM+SSO1SMQ4nqVKWOu8bVszlPmDJkgEWvn9Ltl9sC/oP7oFbqBR1Qd4d/g0OAjyu20q51Wi70/CkYtgRpashrhipq7NawKV4oJ8F+yrf1aVixn36XvkYOnoxNLILAncxV4Ds7cr1SvwHMA6/cattVjK+6IkiwV0KvvZ4GfcXREjxtw5I/UjpnMJr9YKAoAX3lNqtYSECmR72KtoCnyCerV0D19PA8SuAOhAnhijly4egg3T1tO1yIrufee8jxoqsvl35aasBzc5qIwjUFJlQ+9gm1v5hSpOZXasLWaB60q6MTSV69mljJkByTIzeBQ5dCIVAAdVS7bqEuc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/www.shallalist.de
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
