env:
  global:
    - secure: kUVk2kaAr1QVbMnu3y3q+t3fzuDEVAYA0wS7qkScjzeBNH5y7scMe3BllbqFmRIKEWNpwD80TRHzNX1ftsvgshuGXBFDAWA6ucq1gnZm064M0tGxOQy7rv/YXwViBTWrlXZmblVCsfdWB7V4lefwe7XfIsqH2Zn+pU+hAHQ8RaPXyg7gxVR2blBEjcjyXH1dyWm3/3RBKv6GNQmbcfTVCZFssBr0it+FeY1XXEteB74OF3goLpusU9dp8Lvo+TsLGwrAML8dOiXOI93WukZu5h/VeBCBl8R05u0ClJ5aZ2G50vIqz4Ca7afCaWtYxoDS29arDx5LTG/PX3GcWig9NUrVulLWMBJBkiyOsOK4QSIr/IqkG25foIdoF2VhJ0BrpSXCC4dSf1J8mXdOKSZ5KvxjeHC6G/bL1E+emAWj/ixRA/Iv8syRqKRFGoLEJzoGlRYk58zjIllcFniRfvCvT9FJceNCrZ2QWyjl6fa7IMdWRws3pzw1ZIyKnMbVSXegaR77EqL4wWWzrH9rgDP3/wBazd8V5HWU23qiR7eX15eOgzfcHKGkrJ/8Miz85RLB+vn/jOweXpRyCvjQOM/+fmZMTKR0MLcZw5AWqTH6VNNBTLFHseH/WQui9c7YybVKyz7pgY8+vh+N7/1W1/nzAibt9xzNiSRhv6wov7DdlNA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/www.shallalist.de
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
