env:
  global:
    - secure: JLC+5k7WwcB2h+FoJ7DvL/oDaa/2t7LULTzJsKH9Z3enEaO7XJQ1Mxc0M9thZbZjoZoLEccmYHCdof5fZJzbFD43jZZZl11yw5SzWbxrjn7Xx4oPCAh5w60weDMPEIEfR9gG3Akt/X2x2DMsnB/M8JZIgQGhtanjwpyItF42y8PBARrhO6MCinGOsNv00JYlWtbyV1llVoNmI7uRUYkZ9CSPuvHYb1d6N+S02i5WA6wmDDqR9VUh6LjIJYsUAXSCV9nTwyc+LMxEYuyvuKdxRv/ySEegNI1q7C0Or9Pzza94n/CGphOobavOLDHO8CSUdHjLzIf7lWXzXoxi4Pxk2VHmYnjAHbnw18tL/3seJE6EGHPOS6gd6GZ/SQga8fR5xuDHEpIWbuv/CMfr0wqmmqyLbr7YQBBTd4SZ+DEE4wirQJawmdnhniny4+C1pbl3antVG6Sv/cxxQwqzurw2M2NKoNQfNq+wNQS9WFam359htwZhFqccEpeXjgCKV9xwnSc2l0uxVoWTdAGzKurdgJ090SKEwwla5izR+Yxya6xC1r7uZk4wHP9T3w2SOg0NMNG0O41CkzmHbgtHMv5yoF2cAFZKnU5Uq/6WvuxsJDjQvQauFffQNZeY1gROjB0413z77fI0lVvK2fJSV85f2iD287P78BnyQe2OqPpg10w=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/www.shallalist.de
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
