env:
  global:
    - secure: PT9zJ0VFfQ4eFjhKqRI1riUD9T31R96wAfTiDVVUQRc4brCuKqA+sx4EN5oJ2i9rJUNN0KK9lSpLXA0XEAaAJPyxM99rHHujdLObA1KhHNR3ZEjTENIrxErafzwOkk2LELUXTyEj/+g+zQbQK/KznsCOzSf99thcCjgQTiXyRfSJzB9X4Oi6NetoT/CybJd7sc/KlIQhFrPp4n2dQcNpJ9TVFH+N5bxQ4/NK5vt2WhwckRnHv1Kb+n9oyGiHBhXbn7Mjm6Ls+TL989mZUabIWthetCxv9zPaRnK3VgoWC8Z6RFVfn0Tv8jrlL/fvowbZFDPY+miKIeSIospOYubdnbD8y9G/m7bmxhtNIyMGOnjCmtd4VqJWQM/svv3lACvH74FPkdjrGjySWR92oWqfj34gDRL3kZ9jA+D5LKj5tFZhhCuhgfP/+5mzY7ncRTk4It4fKGtIUhtcXoH+n4PD2lFkS9TIu0N4ZzNWEdrggD9CiHufVX2LtYU0bo+GdOv/ucNixwVDpMEqRgyfWKjSgTd4dquqL/hcvRc4LdYUwj9WK5oEFOR8CiIHIu4cFnHVMreDKRfxU0FGlNyRO1HFLxzoM3WoLV0F9xBM8IoU3zcphaqwKReDxCCmDhq5I/jRjmpHCu96AnEvd5MZ2KK6HwfFGhny0lg225VZ8bq2324=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/www.shallalist.de
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
